language: java
dist: trusty
sudo: false
addons:
  apt:
    packages:
    - ttf-ubuntu-font-family
    - inkscape
jdk:
- oraclejdk8
node_js:
- '8'
install:
- nvm install 8
- nvm alias default 8
- npm install
- "./gradlew"
- "./gradlew -p test/resources installDist"
script:
- npm test
- npm start
deploy:
  provider: releases
  api_key:
    secure: kkeTrvgQScj1un5eGica9HfeEIeDnOfQ5FDeZzVYSDOotZ2nbqlsMObGBu9Q3+90/w93x4/y7u+QD3STO0mqGqqUQYH39ghkkZHyQc3h4J+mmcSwpM9thJXrMkbnJUyLh2KV8UcOaCHZ6nF+Qy86AfnvltcBvefp6/VceLJB+rRCxkU6LKMwen1XDgJzwKIpBXU8VuHepKL4qfas8DyYXcxJZfxyKgzyc08csXY1FihPbxE00FiJytzkkWSk3sNpI/Q8W3FupYX5BgJZUlqq21p82yjkODmn0mjDq0Grw9u6LjztphHmYNS5SV5hhowM5FG+M4+Ao3x13/Mk+tvcnm4Tzdg7aSw/jPmS7tSpNJHck2CUu33QfyAmQzxcVi8kV03gR1cGLmb9Y5m6UPrFDcdEkTxib8Eg6Nj160Jg3W5QxeXMvEATqu7v9yltFyPJtf4ObGytfY8CWZK2WnSoXE4vZLLmRmAsVclpFhP2qBjGATSWTCu8QWhVVE0O9INLhW29jy5HK6GKXHxXQ8vyxpcVh54eQTQVhTuUN6AnXUeRDvcuYTt6S8ieUYgPStnH4Dseah3vtvSZdU8ZZnFQ36MnMJHgYmbALPlwnf/DUBMsyA93/arnsd5QFLTp3QjHZ04ea75Zfi+fOYUHMBFVQhPjqNdcCpWJAz/17dJh41A=
  file: vscode-ltex-*.vsix
  file_glob: true
  skip_cleanup: true
  on:
    repo: valentjn/vscode-ltex-languages
    tags: true
after_deploy:
- "./publish-all.sh"
env:
  global:
    secure: rDmPiPb5Nd8v7ur0xDlmivGGF1yeY5h3Dho4OLoF9vubOs1dhxzyWOWMC8TQt5Xpf6ekJaxOMGKOYNUQhcLuSguwLpiUcCMPttwXmPSQ6Wy/aWPAHcLgRwEq1sZgYmVM+0oJfQL3U/i25EBGPYjhnFwh1z+qhwiRyFnjPa/ntGNWGD30scI1TtCwuglf6A9lPETU2USNimdPEPku+rGtFnYy68xFCFninkjoNx/IQaWi64xnCOI3uxtV1ZP3AxfvqI2miQJa1QeZmz01cIEH0YmwSfHGOVsmrTTZCQ5yIyQm7etzwRLvqiduFj5ji3vbAdhLgHA+TMk6un0O0iIdY4mn/sxP7HVyjAD6BCyb6mnlHRhVlE5Sv7JDO1Ld2JvrZe2KdYAZfBvaeb1Dt6wGfw2hXFszYA+Ij16urux535IW3Y5p91I9RhxBhZFq11f1DJ8KFwkJ5VKo7RM3Ryi7mNaQ03J99hm14/4/wXO3NT3LDd6g82RO0QKQT38alpL9JeWif2qmzGHuwqLQ4HVTziF202P5PUUIKHEsuyWNzDAlOEvluJDR+HhpXpLhWK+a6c4esIPb0D/VKei4lPqgEjRLwKfNjrD75x82At149fcNIahbOseAAXdn+c4PwBx3CEdUVb/pXtx4Ty9FnujH9lVteGz1ez4ajI81dLz20Tk=
