language: java
os: linux
dist: trusty
addons:
  apt:
    packages:
    - ttf-ubuntu-font-family
    - inkscape
jdk:
- oraclejdk8
node_js:
- '8'
install:
- nvm install 8
- nvm alias default 8
- npm install
- "./gradlew"
- "./gradlew -p test/resources installDist"
script:
- npm test
- npm start
deploy:
  provider: releases
  token:
    secure: AN82f9QRRME4JKskc9X1z6YBujFFptI5GinBnJniiYwmC/Cu6R45ARTURS87HUsXT5pKjJXCvWuCcwYY2lkMrENUspR714rnJPUdjbgHSJYA2cwHcumSApyNn6/rvRmxQ4k+WP4RDCHIUuNAMw4lvrWQpnjBWWkeZ3kXjt4mY47QvxrTrFvx1obZKr7V0rn9EpGbKJF7u6HOr6JFqFfFild514dtS4DL802DdoGp/AhKsMbUx1b0bjgh0cR4A7DAA0La5ICCkcKoGN+pVSuQpGkjAQ9HnDfhUIa1UVrg/Bx+qrx2JrLZJDtkXG0I731c9e2Fbc94fkpBAOn0ZoFudIAiqzdeK+KlAPb1gN2bYb5OLpHIATy0Sr7MnwcT7oZ2rg5O3Q8jC6YaLQeivSY1fpt3TDV5L6KO5UxdQxxxv3/wbVFooFV2UYoXwLQvJgamfvLl58yMtQ1J4Y+dQfRBgXRwElHhWc2hYEQVK39hPdJbJmYU2n79EbY/68rMx6hZP+aoY7sTARd2dq4lZ3FQsvyOxZo2WRjs1K1cagQVK0VfFM5DGkQZYwGZ4qI9uhfh11FHWWtqo5xPu2Qs7ag7ieMcta0r3WzNNHpHt+6e5UeyOGtcklYuDU9juswSQWSQzEk9i59VjRJrVKbKR5WBlkUsDGHp2nROHO8bkxwdsZI=
  file: vscode-ltex-*.vsix
  file_glob: true
  # needs to be removed for Travis's dpl v2
  # see https://blog.travis-ci.com/2019-08-27-deployment-tooling-dpl-v2-preview-release#cleaning-up-the-git-working-directory
  skip_cleanup: true
  on:
    repo: valentjn/vscode-ltex-languages
    tags: true
after_deploy:
- "./publish-all.sh"
env:
  global:
    secure: HZy1HMQ85JoA0unyxxwZCW1oDmPLZPugSKrConkPPLMkytoPCpLd2jgbdiV/vl/DaINksQZHUXK2iNztidGCexjNSa4AJRNjbxc7YrY74RqcGHdQ+UqmbvGQnSHTaWG7IdEpr4zN/1x62BAcgyz4xmLldsA/kDNNUIU0C44KD+Pv35n2waa8ZWlC17u+V4AMuS6d3UpMjYx19YYurU8+P+mQW8v2Zc3SlVEUnNa1aZkRUUQHJd1arFOAclYn3TC2FoDKLMMi6iopfl+vomiQWhA34e1P+Vwyz0RLSllikQDfTFJuGd+B9kPkrKZe+uPamY6v8G9EGTVBBIuXerrJ+Ml+7c7iazERLcQA0OdQJW4k15EgF7RoJeqJQNQNLSHcJy8SQLNdbdydP+PFGDgsocMvyZ+GCJtRo9jXmp4z/Vn7Ps/sGoIT7gKzqsrRpZr5KaP8olVc1pphB/8wAnGFhPBILJvF7z0/AQnBg+IjiyBmOFUVuRqMkgqn56+s4hS3cMvjC0wfrFO/I/81FfL9eQWr8BXKZHlfL6JLLJL213nYpm2jMLFfs7y+03PHLX5vP2QxDbCCXtYxo0tf6ZwwhmrL70YUgTt6/Hf8130wefN4g2oCdj6dHff/IgWGiyFba7OMjxJUbnfx1jNzTwUX0fEW0zs+Fr2WPtPJLBh6B5o=
